window.CFL_FIGHTERS = {
  "ty-jhonson": {
    id: "ty-jhonson",
    name: "Ty “La Pollona” Jhonson",
    namePlain: "Ty Jhonson",
    nickname: "La Pollona",
    sport: { es: "MMA", en: "MMA" },
    country: { es: "Estados Unidos", en: "United States" },
    countryCode: "us",
    based: { es: "Punta Cana, República Dominicana", en: "Punta Cana, Dominican Republic" },
    image: "assets/ty-jhonson.png?v=6",
    record: "15-8-0",
    division: { es: "Peso pluma", en: "Featherweight" },
    height: "5′7″ / 170 cm",
    reach: "67.3″ / 171 cm",
    stance: { es: "Ortodoxo", en: "Orthodox" },
    koRate: "13%",
    debut: "2019",
    sourceLabel: "Tapology",
    sourceUrl: "https://www.tapology.com/fightcenter/fighters/114445-ty-kalista",
    bio: {
      es: "Atleta de MMA con recorrido internacional (PFL, Titan FC, XKO) y base en Punta Cana. Conocido por su wrestling y submissions, proyecta el talento CFL hacia escenarios globales.",
      en: "An international MMA competitor (PFL, Titan FC, XKO) based in Punta Cana. Known for wrestling and submissions, he brings CFL talent onto global stages.",
    },
    recent: [
      { result: "W", opponent: "Akeem Bashir", event: "CFC 11", date: "2026-08-22", method: "Decision · R3" },
      { result: "L", opponent: "João Felipe Borges", event: "Peak Fighting 45", date: "2025-06-28", method: "KO · R1" },
      { result: "W", opponent: "Tarcísio Romano", event: "Peak Fighting 42", date: "2025-01-25", method: "TKO · R3" },
      { result: "L", opponent: "Bryce Meredith", event: "PFL 1 (2024)", date: "2024-04-04", method: "Decision · R3" },
      { result: "W", opponent: "Motaz Askar", event: "Anthony Pettis FC 9", date: "2023-11-19", method: "Decision · R3" },
    ],
  },

  "branny-rosario": {
    id: "branny-rosario",
    name: "Branny Rosario",
    namePlain: "Branny Rosario",
    nickname: "",
    sport: { es: "MMA", en: "MMA" },
    country: { es: "República Dominicana", en: "Dominican Republic" },
    countryCode: "do",
    based: { es: "Santo Domingo, República Dominicana", en: "Santo Domingo, Dominican Republic" },
    image: "assets/branny-rosario.png?v=6",
    record: "2-0-0",
    division: { es: "Peso pluma / gallo", en: "Featherweight / Bantamweight" },
    height: "5′9″ / 175 cm",
    reach: "—",
    stance: { es: "Ortodoxo", en: "Orthodox" },
    koRate: "50%",
    debut: "2024-07-06",
    sourceLabel: "Tapology",
    sourceUrl: "https://www.tapology.com/fightcenter/fighters/307205-branny-rosario",
    bio: {
      es: "Prospecto dominicano invicto en MMA profesional. Dos victorias en Fighting Force con finalizaciones en el primer asalto.",
      en: "Undefeated Dominican MMA prospect. Two Fighting Force wins, both first-round finishes.",
    },
    recent: [
      { result: "W", opponent: "Tommy Garcia", event: "Fighting Force 16", date: "2025-08-02", method: "Submission · R1" },
      { result: "W", opponent: "Freddy Mordan", event: "Fighting Force 14", date: "2024-07-06", method: "TKO · R1" },
    ],
  },

  "delffy-humer": {
    id: "delffy-humer",
    name: "Delffy “El Guerrero DD” Humer",
    namePlain: "Delffy Humer",
    nickname: "El Guerrero DD",
    sport: { es: "MMA", en: "MMA" },
    country: { es: "República Dominicana", en: "Dominican Republic" },
    countryCode: "do",
    based: { es: "Cabarete / Sosúa, República Dominicana", en: "Cabarete / Sosúa, Dominican Republic" },
    image: "assets/delffy-humer.png?v=6",
    record: "3-0-0",
    division: { es: "Peso mosca", en: "Flyweight" },
    height: "5′8″ / 173 cm",
    reach: "—",
    stance: { es: "Ortodoxo", en: "Orthodox" },
    koRate: "67%",
    debut: "2025-05-17",
    sourceLabel: "Tapology",
    sourceUrl: "https://www.tapology.com/fightcenter/fighters/307971-delffy-humer-el-guerrero-dd",
    bio: {
      es: "Peso mosca dominicano invicto, con experiencia amateur internacional (IMMAF) y tres victorias profesionales en España con The Way of Warrior.",
      en: "Undefeated Dominican flyweight with international amateur experience (IMMAF) and three pro wins in Spain with The Way of Warrior.",
    },
    recent: [
      { result: "W", opponent: "Rafael Gemaque", event: "WOW 27 · Madrid", date: "2026-03-07", method: "TKO · R3" },
      { result: "W", opponent: "Yaman Mjahed", event: "WOW 24 · Vitoria", date: "2025-11-28", method: "KO/TKO · R2" },
      { result: "W", opponent: "Jose Jefferson Cobo Diaz", event: "WOW 19 · Alicante", date: "2025-05-17", method: "Submission · R3" },
    ],
  },

  "carlos-santana": {
    id: "carlos-santana",
    name: "Carlos “El soldado de Dios” Santana",
    namePlain: "Carlos Santana",
    nickname: "El soldado de Dios",
    sport: { es: "MMA", en: "MMA" },
    country: { es: "República Dominicana", en: "Dominican Republic" },
    countryCode: "do",
    based: { es: "Santo Domingo, República Dominicana", en: "Santo Domingo, Dominican Republic" },
    image: "assets/carlos-santana.jpg?v=1",
    record: "5-4-0",
    division: { es: "Peso pluma / ligero", en: "Featherweight / Lightweight" },
    height: "5′8″ / 173 cm",
    reach: "—",
    stance: { es: "Ortodoxo", en: "Orthodox" },
    koRate: "40%",
    debut: "2023",
    sourceLabel: "Tapology",
    sourceUrl: "https://www.tapology.com/fightcenter/fighters/163106-carlos-daniel-santana",
    bio: {
      es: "Peso pluma/ligero dominicano de Team Mordan. Combate en Santo Domingo y en el circuito internacional, con finalizaciones por TKO y submission.",
      en: "Dominican featherweight/lightweight out of Team Mordan. Fights in Santo Domingo and on the international circuit, with finishes by TKO and submission.",
    },
    recent: [
      { result: "W", opponent: "Edwin Andres Gomez", event: "LFC 3", date: "2026-08-27", method: "TKO · R2" },
      { result: "L", opponent: "Brett Pastore", event: "FightWorld 44", date: "2026-03-21", method: "Decision · R3" },
      { result: "L", opponent: "Fabian Miranda", event: "Tough N Xtreme", date: "2025-11-29", method: "Submission · R2" },
      { result: "L", opponent: "Elias Santos", event: "Fighting Force 16", date: "2025-08-02", method: "TKO · R2" },
      { result: "W", opponent: "Andres Gomez", event: "Fighting Force 15", date: "2024-10-19", method: "Decision · R3" },
    ],
  },

  "abraham-nava": {
    id: "abraham-nava",
    name: "Abraham “The Savage” Nava",
    namePlain: "Abraham Nava",
    nickname: "The Savage",
    sport: { es: "MMA", en: "MMA" },
    country: { es: "México", en: "Mexico" },
    countryCode: "mx",
    based: { es: "Michoacán, México", en: "Michoacán, Mexico" },
    image: "assets/abraham-nava.jpg?v=1",
    record: "7-6-0",
    division: { es: "Peso pluma", en: "Featherweight" },
    height: "5′6″ / 168 cm",
    reach: "—",
    stance: { es: "Ortodoxo", en: "Orthodox" },
    koRate: "43%",
    debut: "2019",
    sourceLabel: "Tapology",
    sourceUrl: "https://www.tapology.com/fightcenter/fighters/47705-abraham-nava",
    bio: {
      es: "Peso pluma mexicano conocido como “The Savage”. Veterano de UWC, LUX y BSC, y rival de Ty Jhonson en la premiere CFL.",
      en: "Mexican featherweight known as “The Savage.” A UWC, LUX, and BSC veteran, and Ty Jhonson’s opponent at the CFL premiere.",
    },
    recent: [
      { result: "L", opponent: "Ezequiel de Jesus Peralta", event: "BSC 33", date: "2026-02-26", method: "Decision · R3" },
      { result: "W", opponent: "Braden Aupuni Pagaoa", event: "MMA Mexico 6", date: "2025-10-18", method: "Decision · R3" },
      { result: "L", opponent: "André Barquero", event: "Lux Fight League 48", date: "2024-11-29", method: "Submission · R1" },
      { result: "L", opponent: "Juan Diaz", event: "Lux Fight League 42", date: "2024-04-26", method: "Decision · R3" },
      { result: "W", opponent: "Jefferson Chaves", event: "Lux Fight League 40", date: "2024-02-23", method: "Decision · R3" },
    ],
  },

  "marco-elpidio": {
    id: "marco-elpidio",
    name: "Marco “La Roca” Elpidio",
    namePlain: "Marco Elpidio",
    nickname: "La Roca",
    sport: { es: "MMA", en: "MMA" },
    country: { es: "México", en: "Mexico" },
    countryCode: "mx",
    based: { es: "Ciudad de México, México", en: "Mexico City, Mexico" },
    image: "assets/marco-elpidio.jpg?v=1",
    record: "24-13-2",
    division: { es: "Peso ligero", en: "Lightweight" },
    height: "5′6″ / 168 cm",
    reach: "—",
    stance: { es: "Ortodoxo", en: "Orthodox" },
    koRate: "29%",
    debut: "2013",
    sourceLabel: "Tapology",
    sourceUrl: "https://www.tapology.com/fightcenter/fighters/80303-mario-elpidio-la-rocka",
    bio: {
      es: "Peso ligero mexicano de Brotherhood Arte Violento. Veterano de Combate, UWC y OKTAGON, y rival de Carlos Santana en la premiere CFL.",
      en: "Mexican lightweight out of Brotherhood Arte Violento. A Combate, UWC, and OKTAGON veteran, and Carlos Santana’s opponent at the CFL premiere.",
    },
    recent: [
      { result: "W", opponent: "Edgar Escarrega", event: "SFN 11", date: "2026-04-25", method: "Decision · R3" },
      { result: "L", opponent: "Arijan Topallaj", event: "OKTAGON 83", date: "2026-01-31", method: "Decision · R3" },
      { result: "W", opponent: "Ilja Stojanov", event: "MFC 53", date: "2025-12-06", method: "Decision · R3" },
      { result: "L", opponent: "Ozan Aslaner", event: "OKTAGON 80", date: "2025-11-22", method: "Decision · R3" },
      { result: "W", opponent: "Leonardo Blasco", event: "MFL 1", date: "2025-09-06", method: "TKO · R3" },
    ],
  },

  "joao-victor-melo": {
    id: "joao-victor-melo",
    name: "João Victor “Marroto” Melo",
    namePlain: "João Victor Melo",
    nickname: "Marroto",
    sport: { es: "MMA", en: "MMA" },
    country: { es: "Brasil", en: "Brazil" },
    countryCode: "br",
    based: { es: "Belém, Pará, Brasil", en: "Belém, Pará, Brazil" },
    image: "assets/joao-victor-melo.jpg?v=1",
    record: "5-4-0",
    division: { es: "Peso gallo", en: "Bantamweight" },
    height: "5′8″ / 172 cm",
    reach: "—",
    stance: { es: "Ortodoxo", en: "Orthodox" },
    koRate: "0%",
    debut: "2022-10-15",
    sourceLabel: "Tapology",
    sourceUrl: "https://www.tapology.com/fightcenter/fighters/375732-joao-victor-melo-marroto",
    bio: {
      es: "Peso gallo brasileño de Team Figueiredo en Belém. Cinco victorias profesionales, todas por sumisión, y rival de Branny Rosario en la premiere CFL.",
      en: "Brazilian bantamweight out of Team Figueiredo in Belém. Five professional wins, all by submission, and Branny Rosario’s opponent at the CFL premiere.",
    },
    recent: [
      { result: "L", opponent: "Cláudio Meireles", event: "LFA 229", date: "2026-03-27", method: "Decision · R3" },
      { result: "W", opponent: "Marco Alvarez", event: "FFC 101", date: "2026-02-12", method: "Submission · R1" },
      { result: "L", opponent: "Martin Mansilla", event: "Inka FC 50", date: "2025-06-26", method: "Decision · R3" },
      { result: "L", opponent: "Alexander Chavez", event: "Inka FC 49", date: "2025-04-24", method: "Decision · R3" },
      { result: "L", opponent: "João Vitor Cavalcante", event: "Jungle Fight 134", date: "2025-01-18", method: "TKO · R2" },
    ],
  },

  "ricardo-amador": {
    id: "ricardo-amador",
    name: "Ricardo “Grafite” Amador",
    namePlain: "Ricardo Amador",
    nickname: "Grafite",
    sport: { es: "MMA", en: "MMA" },
    country: { es: "Brasil", en: "Brazil" },
    countryCode: "br",
    based: { es: "Salvaterra, Pará, Brasil", en: "Salvaterra, Pará, Brazil" },
    image: "assets/ricardo-amador.jpg?v=1",
    record: "3-2-0",
    division: { es: "Peso mosca", en: "Flyweight" },
    height: "5′4″ / 163 cm",
    reach: "—",
    stance: { es: "Ortodoxo", en: "Orthodox" },
    koRate: "100%",
    debut: "2021",
    sourceLabel: "Tapology",
    sourceUrl: "https://www.tapology.com/fightcenter/fighters/312315-ricardo-amador-grafite",
    bio: {
      es: "Peso mosca brasileño de Salvaterra, Pará, conocido como “Grafite”. Tres victorias por nocaut y rival de Delffy Humer en la premiere CFL.",
      en: "Brazilian flyweight from Salvaterra, Pará, known as “Grafite.” Three knockout wins, and Delffy Humer’s opponent at the CFL premiere.",
    },
    recent: [
      { result: "W", opponent: "Jhonielton Alves Pinheiro", event: "Ultimate Marajó Fight", date: "2026-09-11", method: "TKO · R2" },
      { result: "L", opponent: "Thyago Silva", event: "Salvaterra Marajó Fight 11", date: "2025-07-05", method: "TKO · R2" },
      { result: "W", opponent: "Ricardo Luenio", event: "DS Fight Night 3", date: "2023-01-27", method: "TKO · R1" },
      { result: "L", opponent: "Denilson Lima", event: "DS Fight Night 2", date: "2021-12-04", method: "TKO · R1" },
      { result: "W", opponent: "Christian da Silva", event: "DS Fight Night 1", date: "2021-09-11", method: "TKO · R1" },
    ],
  },

  "tommy-hyde": {
    id: "tommy-hyde",
    name: "Tommy “The Governor” Hyde",
    namePlain: "Tommy Hyde",
    nickname: "The Governor",
    sport: { es: "Boxeo", en: "Boxing" },
    country: { es: "Irlanda", en: "Ireland" },
    countryCode: "ie",
    based: { es: "Cork, Irlanda", en: "Cork, Ireland" },
    image: "assets/tommy-hyde.jpg?v=1",
    record: "14-0-0",
    division: { es: "Súper mediano", en: "Super middleweight" },
    height: "6′4″ / 193 cm",
    reach: "—",
    stance: { es: "Ortodoxo", en: "Orthodox" },
    koRate: "64%",
    debut: "2022-12-01",
    sourceLabel: "BoxRec",
    sourceUrl: "https://boxrec.com/en/box-pro/924045",
    bio: {
      es: "Super mediano irlandés invicto de Cork, conocido como “The Governor”. Catorce victorias profesionales y campeón celta de la BUI, con proyección internacional hacia la noche CFL.",
      en: "Undefeated Irish super middleweight from Cork, known as “The Governor.” Fourteen professional wins and a BUI Celtic champion, lined up for CFL’s Santo Domingo night.",
    },
    recent: [
      { result: "W", opponent: "Vaughn Williams", event: "Santa Monica Pier", date: "2026-08-22", method: "KO · R4" },
      { result: "W", opponent: "Patrick Allotey", event: "Down & Dirty XVIII, Melrose", date: "2025-09-20", method: "Decision · R8" },
      { result: "W", opponent: "Marcos Vinicius de Barros", event: "Boxing Dreams VIII, Villarreal", date: "2025-06-28", method: "Decision · R8" },
      { result: "W", opponent: "Anuary Mlawa", event: "SLB Fight Night, Melbourne Pavilion", date: "2025-04-11", method: "KO/TKO · R1" },
      { result: "W", opponent: "Aro Schwartz", event: "Halloween Knock Out, Club Lido", date: "2024-10-25", method: "KO/TKO · R3" },
    ],
  },

  "kurt-scoby": {
    id: "kurt-scoby",
    name: "Kurt Scoby",
    namePlain: "Kurt Scoby",
    nickname: "",
    sport: { es: "Boxeo", en: "Boxing" },
    country: { es: "Estados Unidos", en: "United States" },
    countryCode: "us",
    based: { es: "Springfield, Massachusetts", en: "Springfield, Massachusetts" },
    image: "assets/kurt-scoby.jpg?v=1",
    record: "20-2-0",
    division: { es: "Súper ligero", en: "Super lightweight" },
    height: "5′9″ / 175 cm",
    reach: "69″ / 175 cm",
    stance: { es: "Ortodoxo", en: "Orthodox" },
    koRate: "90%",
    debut: "2020-09-26",
    sourceLabel: "BoxRec",
    sourceUrl: "https://boxrec.com/en/box-pro/963639",
    bio: {
      es: "Superligero estadounidense de Springfield, Massachusetts. Veinte victorias profesionales —dieciocho por nocaut— y contendiente reciente por el título intercontinental WBO.",
      en: "American super lightweight out of Springfield, Massachusetts. Twenty professional wins —eighteen by knockout— and a recent WBO Inter-Continental title challenger.",
    },
    recent: [
      { result: "W", opponent: "Alfredo Rodolfo Blanco", event: "Philly Fight Night 7, 2300 Arena", date: "2026-08-07", method: "TKO · R4" },
      { result: "W", opponent: "Cristian Perez Hernandez", event: "Wilkes-Barre, Pennsylvania", date: "2026-03-07", method: "KO · R1" },
      { result: "L", opponent: "Adam Azim", event: "Tottenham Hotspur Stadium", date: "2025-11-15", method: "TKO · R12" },
      { result: "W", opponent: "Alex Martin", event: "Boxing Insider 18, Sony Hall", date: "2025-09-19", method: "TKO · R8" },
      { result: "W", opponent: "Haskell Rhodes", event: "OTX 14, 2300 Arena", date: "2025-06-13", method: "RTD · R6" },
    ],
  },

  "miguel-arias": {
    id: "miguel-arias",
    name: "Miguel Angel “Brazo” Arias",
    namePlain: "Miguel Angel Arias",
    nickname: "Brazo",
    sport: { es: "Boxeo", en: "Boxing" },
    country: { es: "República Dominicana", en: "Dominican Republic" },
    countryCode: "do",
    based: { es: "Santo Domingo, República Dominicana", en: "Santo Domingo, Dominican Republic" },
    image: "assets/miguel-arias.jpg?v=2",
    record: "8-0-0",
    division: { es: "Súper wélter", en: "Super welterweight" },
    height: "6′0″ / 183 cm",
    reach: "—",
    stance: { es: "Ortodoxo", en: "Orthodox" },
    koRate: "100%",
    debut: "2024-06-28",
    sourceLabel: "BoxRec",
    sourceUrl: "https://boxrec.com/en/box-pro/1155462",
    bio: {
      es: "Boxeador dominicano invicto de Santo Domingo. Superwélter con ocho victorias profesionales, todas por nocaut, y parte del talento local CFL.",
      en: "Undefeated Dominican boxer from Santo Domingo. A super welterweight with eight pro wins, all by knockout, and part of CFL’s local talent.",
    },
    recent: [
      { result: "W", opponent: "Jose Manuel Perez", event: "Dominican Fight Night, Coliseo Carlos Teo Cruz", date: "2026-09-11", method: "TKO · R3" },
      { result: "W", opponent: "Mario Emilio Ruiz Castillo", event: "Coliseo Carlos Teo Cruz", date: "2025-12", method: "KO/TKO · R4" },
      { result: "W", opponent: "Cristian Camilo Montero", event: "Club Mauricio Báez", date: "2025-03", method: "KO/TKO · R6" },
      { result: "W", opponent: "Luis Enrique Reyes Acatitla", event: "Pabellón de Karate, Centro Olímpico", date: "2024-12", method: "KO/TKO · R4" },
      { result: "W", opponent: "Leonardo Espinal", event: "Santo Domingo", date: "2024-10", method: "KO/TKO · R5" },
    ],
  },

  "rohan-polanco": {
    id: "rohan-polanco",
    name: "Rohan “El Rayo” Polanco",
    namePlain: "Rohan Polanco",
    nickname: "El Rayo",
    sport: { es: "Boxeo", en: "Boxing" },
    country: { es: "República Dominicana", en: "Dominican Republic" },
    countryCode: "do",
    based: { es: "Santo Domingo, República Dominicana", en: "Santo Domingo, Dominican Republic" },
    image: "assets/rohan-polanco.jpg?v=1",
    record: "18-0-0",
    division: { es: "Peso wélter", en: "Welterweight" },
    height: "5′10″ / 178 cm",
    reach: "70″ / 178 cm",
    stance: { es: "Ortodoxo", en: "Orthodox" },
    koRate: "56%",
    debut: "2020-09-19",
    sourceLabel: "BoxRec",
    sourceUrl: "https://boxrec.com/en/box-pro/852484",
    bio: {
      es: "Wélter dominicano invicto de Santo Domingo, conocido como “El Rayo”. Olímpico en Tokio 2020, dieciocho victorias profesionales y campeón intercontinental WBO.",
      en: "Undefeated Dominican welterweight from Santo Domingo, known as “El Rayo.” A Tokyo 2020 Olympian with eighteen pro wins and a WBO Inter-Continental title.",
    },
    recent: [
      { result: "W", opponent: "Alex Martin", event: "Palacio de Recreación, Mayagüez", date: "2026-05-30", method: "Decision · R10" },
      { result: "W", opponent: "Quinton Randall", event: "The Theater at Madison Square Garden", date: "2025-07-26", method: "Decision · R10" },
      { result: "W", opponent: "Fabián Maidana", event: "T-Mobile Arena", date: "2025-05-04", method: "Decision · R10" },
      { result: "W", opponent: "Jean Carlos Torres", event: "The Theater at Madison Square Garden", date: "2025-02-14", method: "TKO · R2" },
      { result: "W", opponent: "Marcelino Nicolas Lopez", event: "The Theater at Madison Square Garden", date: "2024-09-27", method: "TKO · R6" },
    ],
  },

  "edwin-de-los-santos": {
    id: "edwin-de-los-santos",
    name: "Edwin “La Granada” De Los Santos",
    namePlain: "Edwin De Los Santos",
    nickname: "La Granada",
    sport: { es: "Boxeo", en: "Boxing" },
    country: { es: "República Dominicana", en: "Dominican Republic" },
    countryCode: "do",
    based: { es: "Santo Domingo, República Dominicana", en: "Santo Domingo, Dominican Republic" },
    image: "assets/edwin-de-los-santos.jpg?v=1",
    record: "17-3-0",
    division: { es: "Peso ligero", en: "Lightweight" },
    height: "5′8″ / 173 cm",
    reach: "70″ / 178 cm",
    stance: { es: "Zurdo", en: "Southpaw" },
    koRate: "88%",
    debut: "2018-08-25",
    sourceLabel: "BoxRec",
    sourceUrl: "https://boxrec.com/en/box-pro/854612",
    bio: {
      es: "Ligero dominicano de Santo Domingo, conocido como “La Granada”. Diecisiete victorias profesionales —quince por nocaut— y retador al título mundial WBC ante Shakur Stevenson.",
      en: "Dominican lightweight from Santo Domingo, known as “La Granada.” Seventeen professional wins —fifteen by knockout— and a former WBC world title challenger against Shakur Stevenson.",
    },
    recent: [
      { result: "L", opponent: "José Valenzuela", event: "The Cosmopolitan, Las Vegas", date: "2026-06-28", method: "KO · R2" },
      { result: "W", opponent: "Eliot Chavez", event: "Coliseo Carlos Teo Cruz", date: "2025-12-13", method: "TKO · R1" },
      { result: "L", opponent: "Shakur Stevenson", event: "T-Mobile Arena", date: "2023-11-16", method: "Decision · R12" },
      { result: "W", opponent: "Joseph Adorno", event: "Boardwalk Hall, Atlantic City", date: "2023-07-08", method: "Decision · R10" },
      { result: "W", opponent: "José Valenzuela", event: "Crypto.com Arena", date: "2022-09-04", method: "KO · R3" },
    ],
  },
};
