window.CFL_FIGHTERS = {
  "ty-jhonson": {
    id: "ty-jhonson",
    name: "Ty “La Pollona” Jhonson",
    namePlain: "Ty Jhonson",
    nickname: "La Pollona",
    sport: { es: "MMA", en: "MMA" },
    country: { es: "Estados Unidos", en: "United States" },
    countryCode: "us",
    based: { es: "Punta Cana, República Dominicana", en: "Punta Cana, Dominican Republic" },
    image: "assets/ty-jhonson.png?v=6",
    record: "15-8-0",
    division: { es: "Peso pluma", en: "Featherweight" },
    height: "5′7″ / 170 cm",
    reach: "67.3″ / 171 cm",
    stance: { es: "Ortodoxo", en: "Orthodox" },
    koRate: "13%",
    debut: "2019",
    sourceLabel: "Tapology",
    sourceUrl: "https://www.tapology.com/fightcenter/fighters/114445-ty-kalista",
    bio: {
      es: "Atleta de MMA con recorrido internacional (PFL, Titan FC, XKO) y base en Punta Cana. Conocido por su wrestling y submissions, proyecta el talento CFL hacia escenarios globales.",
      en: "An international MMA competitor (PFL, Titan FC, XKO) based in Punta Cana. Known for wrestling and submissions, he brings CFL talent onto global stages.",
    },
    recent: [
      { result: "W", opponent: "Akeem Bashir", event: "CFC 11", date: "2026-08-22", method: "Decision · R3" },
      { result: "L", opponent: "João Felipe Borges", event: "Peak Fighting 45", date: "2025-06-28", method: "KO · R1" },
      { result: "W", opponent: "Tarcísio Romano", event: "Peak Fighting 42", date: "2025-01-25", method: "TKO · R3" },
      { result: "L", opponent: "Bryce Meredith", event: "PFL 1 (2024)", date: "2024-04-04", method: "Decision · R3" },
      { result: "W", opponent: "Motaz Askar", event: "Anthony Pettis FC 9", date: "2023-11-19", method: "Decision · R3" },
    ],
  },

  "thomas-blumenfeld": {
    id: "thomas-blumenfeld",
    name: "Thomas Blumenfeld",
    namePlain: "Thomas Blumenfeld",
    nickname: "The Bullet",
    sport: { es: "Boxeo", en: "Boxing" },
    country: { es: "Canadá", en: "Canada" },
    countryCode: "ca",
    based: { es: "Springfield, Vermont / Canadá", en: "Springfield, Vermont / Canada" },
    image: "assets/thomas-blumenfeld.png?v=6",
    record: "12-0-0",
    division: { es: "Ligero / Superligero", en: "Lightweight / Light welterweight" },
    height: "—",
    reach: "—",
    stance: { es: "Zurdo", en: "Southpaw" },
    koRate: "83%",
    debut: "2022-06-11",
    sourceLabel: "BoxRec",
    sourceUrl: "https://boxrec.com/en/box-pro/864573",
    bio: {
      es: "Prospecto canadiense invicto con plata en los Juegos de la Commonwealth 2018. Southpaw con alto porcentaje de nocauts y proyección internacional hacia la noche CFL en Santo Domingo.",
      en: "Undefeated Canadian prospect and 2018 Commonwealth Games silver medalist. A southpaw with a high knockout rate, lined up for CFL’s Santo Domingo night.",
    },
    recent: [
      { result: "W", opponent: "Willmank Canonico Brito", event: "Mohegan Sun Pocono Downs", date: "2026-03", method: "Decision" },
      { result: "W", opponent: "Cristian Ruben Mino", event: "Mohegan Fall Brawl", date: "2025-11", method: "KO/TKO · R1" },
      { result: "W", opponent: "Julio Rosa", event: "Carteret, NJ", date: "2025-09", method: "KO/TKO · R4" },
      { result: "W", opponent: "Christopher Rodriguez", event: "Carteret, NJ", date: "2025-04", method: "KO/TKO · R3" },
      { result: "W", opponent: "Frankie Sanchez Jr", event: "2300 Arena, Philadelphia", date: "2025-03", method: "KO/TKO · R2" },
    ],
  },

  "vincent-vangogh": {
    id: "vincent-vangogh",
    name: "Vincent “El Cuco” Van Gogh",
    namePlain: "Vincent Van Gogh",
    nickname: "El Cuco",
    sport: { es: "MMA", en: "MMA" },
    country: { es: "República Dominicana", en: "Dominican Republic" },
    countryCode: "do",
    based: { es: "Santo Domingo, República Dominicana", en: "Santo Domingo, Dominican Republic" },
    image: "assets/vincent-vangogh.png?v=6",
    record: "6-3-0 (1 NC)",
    division: { es: "Peso pluma", en: "Featherweight" },
    height: "5′8″ / 173 cm",
    reach: "—",
    stance: { es: "Ortodoxo", en: "Orthodox" },
    koRate: "83%",
    debut: "2020",
    sourceLabel: "Tapology",
    sourceUrl: "https://www.tapology.com/fightcenter/fighters/244282-vincent-van-gogh",
    bio: {
      es: "Peso pluma dominicano y campeón FFP. Estilo agresivo con alto porcentaje de finales por KO/TKO, representante local de la cultura de combate en Santo Domingo.",
      en: "Dominican featherweight and FFP champion. Aggressive finisher with a high KO/TKO rate — a hometown face of combat culture in Santo Domingo.",
    },
    recent: [
      { result: "W", opponent: "Juan Carlos Alcantara", event: "Fighting Force 15", date: "2024-10-19", method: "Submission · R1" },
      { result: "NC", opponent: "Edwin Andres Gomez", event: "Fighting Force 14", date: "2024-07-06", method: "No contest · R2" },
      { result: "W", opponent: "Yeison Bayona", event: "Fighting Force 13", date: "2024-02-03", method: "KO · R1" },
      { result: "W", opponent: "Alex Alcantara", event: "Fighting Force 12", date: "2023-09-02", method: "TKO · R1" },
      { result: "L", opponent: "Luis Miguel Aular", event: "Liga Inmortal 2", date: "2023-03-04", method: "TKO · R3" },
    ],
  },

  "yancarlos-perez": {
    id: "yancarlos-perez",
    name: "Yancarlos Perez",
    namePlain: "Yancarlos Perez",
    nickname: "",
    sport: { es: "Boxeo", en: "Boxing" },
    country: { es: "República Dominicana", en: "Dominican Republic" },
    countryCode: "do",
    based: { es: "Santo Domingo, República Dominicana", en: "Santo Domingo, Dominican Republic" },
    image: "assets/yancarlos-perez.png?v=6",
    record: "8-1-1",
    division: { es: "Súper gallo", en: "Super bantamweight" },
    height: "5′6″ / 168 cm",
    reach: "—",
    stance: { es: "Ortodoxo", en: "Orthodox" },
    koRate: "63%",
    debut: "2024-06-28",
    sourceLabel: "BoxRec",
    sourceUrl: "https://boxrec.com/en/box-pro/1081310",
    bio: {
      es: "Boxeador dominicano de Villa Mella con debut profesional en 2024. Cartelera activa entre Santo Domingo y Estados Unidos, y parte del talento local CFL.",
      en: "Dominican boxer from Villa Mella who turned pro in 2024. Active between Santo Domingo and the U.S., and part of CFL’s local talent pipeline.",
    },
    recent: [
      { result: "D", opponent: "Juan Alcantara Sanchez", event: "Dominican Fight Night, Coliseo Carlos Teo Cruz", date: "2026-09-11", method: "Draw · R8" },
      { result: "W", opponent: "Carlos Alberto Santana Parra", event: "Coliseo Carlos Teo Cruz", date: "2025-12", method: "Win" },
      { result: "W", opponent: "Gregorio Lebron", event: "Revere, Massachusetts", date: "2025-11", method: "Win" },
      { result: "L", opponent: "Rajon Chance", event: "White Plains, New York", date: "2025-06", method: "Loss" },
      { result: "W", opponent: "Merlito Sabillo", event: "Pueblo, Colorado", date: "2025-05", method: "Win" },
    ],
  },

  "branny-rosario": {
    id: "branny-rosario",
    name: "Branny Rosario",
    namePlain: "Branny Rosario",
    nickname: "",
    sport: { es: "MMA", en: "MMA" },
    country: { es: "República Dominicana", en: "Dominican Republic" },
    countryCode: "do",
    based: { es: "Santo Domingo, República Dominicana", en: "Santo Domingo, Dominican Republic" },
    image: "assets/branny-rosario.png?v=6",
    record: "2-0-0",
    division: { es: "Peso pluma / gallo", en: "Featherweight / Bantamweight" },
    height: "5′9″ / 175 cm",
    reach: "—",
    stance: { es: "Ortodoxo", en: "Orthodox" },
    koRate: "50%",
    debut: "2024-07-06",
    sourceLabel: "Tapology",
    sourceUrl: "https://www.tapology.com/fightcenter/fighters/307205-branny-rosario",
    bio: {
      es: "Prospecto dominicano invicto en MMA profesional. Dos victorias en Fighting Force con finalizaciones en el primer asalto.",
      en: "Undefeated Dominican MMA prospect. Two Fighting Force wins, both first-round finishes.",
    },
    recent: [
      { result: "W", opponent: "Tommy Garcia", event: "Fighting Force 16", date: "2025-08-02", method: "Submission · R1" },
      { result: "W", opponent: "Freddy Mordan", event: "Fighting Force 14", date: "2024-07-06", method: "TKO · R1" },
    ],
  },

  "delffy-humer": {
    id: "delffy-humer",
    name: "Delffy “El Guerrero DD” Humer",
    namePlain: "Delffy Humer",
    nickname: "El Guerrero DD",
    sport: { es: "MMA", en: "MMA" },
    country: { es: "República Dominicana", en: "Dominican Republic" },
    countryCode: "do",
    based: { es: "Cabarete / Sosúa, República Dominicana", en: "Cabarete / Sosúa, Dominican Republic" },
    image: "assets/delffy-humer.png?v=6",
    record: "3-0-0",
    division: { es: "Peso mosca", en: "Flyweight" },
    height: "5′8″ / 173 cm",
    reach: "—",
    stance: { es: "Ortodoxo", en: "Orthodox" },
    koRate: "67%",
    debut: "2025-05-17",
    sourceLabel: "Tapology",
    sourceUrl: "https://www.tapology.com/fightcenter/fighters/307971-delffy-humer-el-guerrero-dd",
    bio: {
      es: "Peso mosca dominicano invicto, con experiencia amateur internacional (IMMAF) y tres victorias profesionales en España con The Way of Warrior.",
      en: "Undefeated Dominican flyweight with international amateur experience (IMMAF) and three pro wins in Spain with The Way of Warrior.",
    },
    recent: [
      { result: "W", opponent: "Rafael Gemaque", event: "WOW 27 · Madrid", date: "2026-03-07", method: "TKO · R3" },
      { result: "W", opponent: "Yaman Mjahed", event: "WOW 24 · Vitoria", date: "2025-11-28", method: "KO/TKO · R2" },
      { result: "W", opponent: "Jose Jefferson Cobo Diaz", event: "WOW 19 · Alicante", date: "2025-05-17", method: "Submission · R3" },
    ],
  },

  "carlos-santana": {
    id: "carlos-santana",
    name: "Carlos “El soldado de Dios” Santana",
    namePlain: "Carlos Santana",
    nickname: "El soldado de Dios",
    sport: { es: "MMA", en: "MMA" },
    country: { es: "República Dominicana", en: "Dominican Republic" },
    countryCode: "do",
    based: { es: "Santo Domingo, República Dominicana", en: "Santo Domingo, Dominican Republic" },
    image: "assets/carlos-santana.jpg?v=1",
    record: "5-4-0",
    division: { es: "Peso pluma / ligero", en: "Featherweight / Lightweight" },
    height: "5′8″ / 173 cm",
    reach: "—",
    stance: { es: "Ortodoxo", en: "Orthodox" },
    koRate: "40%",
    debut: "2023",
    sourceLabel: "Tapology",
    sourceUrl: "https://www.tapology.com/fightcenter/fighters/163106-carlos-daniel-santana",
    bio: {
      es: "Peso pluma/ligero dominicano de Team Mordan. Combate en Santo Domingo y en el circuito internacional, con finalizaciones por TKO y submission.",
      en: "Dominican featherweight/lightweight out of Team Mordan. Fights in Santo Domingo and on the international circuit, with finishes by TKO and submission.",
    },
    recent: [
      { result: "W", opponent: "Edwin Andres Gomez", event: "LFC 3", date: "2026-08-27", method: "TKO · R2" },
      { result: "L", opponent: "Brett Pastore", event: "FightWorld 44", date: "2026-03-21", method: "Decision · R3" },
      { result: "L", opponent: "Fabian Miranda", event: "Tough N Xtreme", date: "2025-11-29", method: "Submission · R2" },
      { result: "L", opponent: "Elias Santos", event: "Fighting Force 16", date: "2025-08-02", method: "TKO · R2" },
      { result: "W", opponent: "Andres Gomez", event: "Fighting Force 15", date: "2024-10-19", method: "Decision · R3" },
    ],
  },

  "andrew-whitney": {
    id: "andrew-whitney",
    name: "Andrew “The Beast” Whitney",
    namePlain: "Andrew Whitney",
    nickname: "The Beast",
    sport: { es: "MMA", en: "MMA" },
    country: { es: "Estados Unidos", en: "United States" },
    countryCode: "us",
    based: { es: "Springfield, Missouri", en: "Springfield, Missouri" },
    image: "assets/andrew-whitney.jpg?v=1",
    record: "16-11-0",
    division: { es: "Peso gallo", en: "Bantamweight" },
    height: "5′7″ / 171 cm",
    reach: "66″ / 168 cm",
    stance: { es: "Ortodoxo", en: "Orthodox" },
    koRate: "44%",
    debut: "2009",
    sourceLabel: "Tapology",
    sourceUrl: "https://www.tapology.com/fightcenter/fighters/17502-andrew-whitney",
    bio: {
      es: "Veterano estadounidense de peso gallo, conocido como “The Beast”. Ha competido en Titan FC y Combate Global, con base en Springfield, Missouri.",
      en: "American bantamweight veteran known as “The Beast.” A Titan FC and Combate Global competitor based in Springfield, Missouri.",
    },
    recent: [
      { result: "L", opponent: "Carlos Briseño", event: "Combate Global", date: "2022-07-01", method: "Decision · R3" },
      { result: "L", opponent: "Martín Bravo", event: "Combate Global", date: "2021-09-17", method: "TKO · R1" },
      { result: "L", opponent: "Ali AlQaisi", event: "Titan FC 71", date: "2021-08-06", method: "Decision · R5" },
      { result: "L", opponent: "Jason Soares", event: "Titan FC 56", date: "2019-08-23", method: "Submission · R2" },
      { result: "L", opponent: "Steve Garcia", event: "Jackson-Wink Fight Night 5", date: "2019-05-10", method: "TKO · R1" },
    ],
  },

  "abraham-nava": {
    id: "abraham-nava",
    name: "Abraham “The Savage” Nava",
    namePlain: "Abraham Nava",
    nickname: "The Savage",
    sport: { es: "MMA", en: "MMA" },
    country: { es: "México", en: "Mexico" },
    countryCode: "mx",
    based: { es: "Michoacán, México", en: "Michoacán, Mexico" },
    image: "assets/abraham-nava.jpg?v=1",
    record: "7-6-0",
    division: { es: "Peso pluma", en: "Featherweight" },
    height: "5′6″ / 168 cm",
    reach: "—",
    stance: { es: "Ortodoxo", en: "Orthodox" },
    koRate: "43%",
    debut: "2019",
    sourceLabel: "Tapology",
    sourceUrl: "https://www.tapology.com/fightcenter/fighters/47705-abraham-nava",
    bio: {
      es: "Peso pluma mexicano conocido como “The Savage”. Veterano de UWC, LUX y BSC, y rival de Ty Jhonson en la premiere CFL.",
      en: "Mexican featherweight known as “The Savage.” A UWC, LUX, and BSC veteran, and Ty Jhonson’s opponent at the CFL premiere.",
    },
    recent: [
      { result: "L", opponent: "Ezequiel de Jesus Peralta", event: "BSC 33", date: "2026-02-26", method: "Decision · R3" },
      { result: "W", opponent: "Braden Aupuni Pagaoa", event: "MMA Mexico 6", date: "2025-10-18", method: "Decision · R3" },
      { result: "L", opponent: "André Barquero", event: "Lux Fight League 48", date: "2024-11-29", method: "Submission · R1" },
      { result: "L", opponent: "Juan Diaz", event: "Lux Fight League 42", date: "2024-04-26", method: "Decision · R3" },
      { result: "W", opponent: "Jefferson Chaves", event: "Lux Fight League 40", date: "2024-02-23", method: "Decision · R3" },
    ],
  },

  "marco-elpidio": {
    id: "marco-elpidio",
    name: "Marco “La Roca” Elpidio",
    namePlain: "Marco Elpidio",
    nickname: "La Roca",
    sport: { es: "MMA", en: "MMA" },
    country: { es: "México", en: "Mexico" },
    countryCode: "mx",
    based: { es: "Ciudad de México, México", en: "Mexico City, Mexico" },
    image: "assets/marco-elpidio.jpg?v=1",
    record: "24-13-2",
    division: { es: "Peso ligero", en: "Lightweight" },
    height: "5′6″ / 168 cm",
    reach: "—",
    stance: { es: "Ortodoxo", en: "Orthodox" },
    koRate: "29%",
    debut: "2013",
    sourceLabel: "Tapology",
    sourceUrl: "https://www.tapology.com/fightcenter/fighters/80303-mario-elpidio-la-rocka",
    bio: {
      es: "Peso ligero mexicano de Brotherhood Arte Violento. Veterano de Combate, UWC y OKTAGON, y rival de Carlos Santana en la premiere CFL.",
      en: "Mexican lightweight out of Brotherhood Arte Violento. A Combate, UWC, and OKTAGON veteran, and Carlos Santana’s opponent at the CFL premiere.",
    },
    recent: [
      { result: "W", opponent: "Edgar Escarrega", event: "SFN 11", date: "2026-04-25", method: "Decision · R3" },
      { result: "L", opponent: "Arijan Topallaj", event: "OKTAGON 83", date: "2026-01-31", method: "Decision · R3" },
      { result: "W", opponent: "Ilja Stojanov", event: "MFC 53", date: "2025-12-06", method: "Decision · R3" },
      { result: "L", opponent: "Ozan Aslaner", event: "OKTAGON 80", date: "2025-11-22", method: "Decision · R3" },
      { result: "W", opponent: "Leonardo Blasco", event: "MFL 1", date: "2025-09-06", method: "TKO · R3" },
    ],
  },

  "valentyn-bulat": {
    id: "valentyn-bulat",
    name: "Valentyn Bulat",
    namePlain: "Valentyn Bulat",
    nickname: "",
    sport: { es: "MMA", en: "MMA" },
    country: { es: "Ucrania", en: "Ukraine" },
    countryCode: "ua",
    based: { es: "Abbotsford, Columbia Británica", en: "Abbotsford, British Columbia" },
    image: "assets/valentyn-bulat.jpg?v=1",
    record: "4-0-0",
    division: { es: "Peso gallo", en: "Bantamweight" },
    height: "—",
    reach: "—",
    stance: { es: "Ortodoxo", en: "Orthodox" },
    koRate: "25%",
    debut: "2025",
    sourceLabel: "Tapology",
    sourceUrl: "https://www.tapology.com/fightcenter/fighters/325471-valentyn-bulat",
    bio: {
      es: "Peso gallo ucraniano invicto, con base en Canadá. Cuatro victorias profesionales y rival de Branny Rosario en la premiere CFL.",
      en: "Undefeated Ukrainian bantamweight based in Canada. Four professional wins, and Branny Rosario’s opponent at the CFL premiere.",
    },
    recent: [
      { result: "W", opponent: "Nichollas Pestili", event: "Samourai MMA 21", date: "2026-09-04", method: "TKO · R1" },
      { result: "W", opponent: "Arturo Reyes Castañeda", event: "BFL 85", date: "2025-10-16", method: "Decision · R3" },
      { result: "W", opponent: "Jordan Meloche", event: "BFL 83", date: "2025-04-17", method: "Submission · R1" },
      { result: "W", opponent: "James Torres", event: "BFL 82", date: "2025-01-23", method: "Decision · R3" },
    ],
  },

  "ricardo-amador": {
    id: "ricardo-amador",
    name: "Ricardo “Grafite” Amador",
    namePlain: "Ricardo Amador",
    nickname: "Grafite",
    sport: { es: "MMA", en: "MMA" },
    country: { es: "Brasil", en: "Brazil" },
    countryCode: "br",
    based: { es: "Salvaterra, Pará, Brasil", en: "Salvaterra, Pará, Brazil" },
    image: "assets/ricardo-amador.jpg?v=1",
    record: "3-2-0",
    division: { es: "Peso mosca", en: "Flyweight" },
    height: "5′4″ / 163 cm",
    reach: "—",
    stance: { es: "Ortodoxo", en: "Orthodox" },
    koRate: "100%",
    debut: "2021",
    sourceLabel: "Tapology",
    sourceUrl: "https://www.tapology.com/fightcenter/fighters/312315-ricardo-amador-grafite",
    bio: {
      es: "Peso mosca brasileño de Salvaterra, Pará, conocido como “Grafite”. Tres victorias por nocaut y rival de Delffy Humer en la premiere CFL.",
      en: "Brazilian flyweight from Salvaterra, Pará, known as “Grafite.” Three knockout wins, and Delffy Humer’s opponent at the CFL premiere.",
    },
    recent: [
      { result: "W", opponent: "Jhonielton Alves Pinheiro", event: "Ultimate Marajó Fight", date: "2026-09-11", method: "TKO · R2" },
      { result: "L", opponent: "Thyago Silva", event: "Salvaterra Marajó Fight 11", date: "2025-07-05", method: "TKO · R2" },
      { result: "W", opponent: "Ricardo Luenio", event: "DS Fight Night 3", date: "2023-01-27", method: "TKO · R1" },
      { result: "L", opponent: "Denilson Lima", event: "DS Fight Night 2", date: "2021-12-04", method: "TKO · R1" },
      { result: "W", opponent: "Christian da Silva", event: "DS Fight Night 1", date: "2021-09-11", method: "TKO · R1" },
    ],
  },

  "miguel-arias": {
    id: "miguel-arias",
    name: "Miguel Angel “Brazo” Arias",
    namePlain: "Miguel Angel Arias",
    nickname: "Brazo",
    sport: { es: "Boxeo", en: "Boxing" },
    country: { es: "República Dominicana", en: "Dominican Republic" },
    countryCode: "do",
    based: { es: "Santo Domingo, República Dominicana", en: "Santo Domingo, Dominican Republic" },
    image: "assets/miguel-arias.jpg?v=2",
    record: "8-0-0",
    division: { es: "Súper wélter", en: "Super welterweight" },
    height: "6′0″ / 183 cm",
    reach: "—",
    stance: { es: "Ortodoxo", en: "Orthodox" },
    koRate: "100%",
    debut: "2024-06-28",
    sourceLabel: "BoxRec",
    sourceUrl: "https://boxrec.com/en/box-pro/1155462",
    bio: {
      es: "Boxeador dominicano invicto de Santo Domingo. Superwélter con ocho victorias profesionales, todas por nocaut, y parte del talento local CFL.",
      en: "Undefeated Dominican boxer from Santo Domingo. A super welterweight with eight pro wins, all by knockout, and part of CFL’s local talent.",
    },
    recent: [
      { result: "W", opponent: "Jose Manuel Perez", event: "Dominican Fight Night, Coliseo Carlos Teo Cruz", date: "2026-09-11", method: "TKO · R3" },
      { result: "W", opponent: "Mario Emilio Ruiz Castillo", event: "Coliseo Carlos Teo Cruz", date: "2025-12", method: "KO/TKO · R4" },
      { result: "W", opponent: "Cristian Camilo Montero", event: "Club Mauricio Báez", date: "2025-03", method: "KO/TKO · R6" },
      { result: "W", opponent: "Luis Enrique Reyes Acatitla", event: "Pabellón de Karate, Centro Olímpico", date: "2024-12", method: "KO/TKO · R4" },
      { result: "W", opponent: "Leonardo Espinal", event: "Santo Domingo", date: "2024-10", method: "KO/TKO · R5" },
    ],
  },

  "elvis-del-castillo": {
    id: "elvis-del-castillo",
    name: "Elvis Del Castillo",
    namePlain: "Elvis Del Castillo",
    nickname: "",
    sport: { es: "Boxeo", en: "Boxing" },
    country: { es: "República Dominicana", en: "Dominican Republic" },
    countryCode: "do",
    based: { es: "Santo Domingo, República Dominicana", en: "Santo Domingo, Dominican Republic" },
    image: "assets/elvis-del-castillo.jpg?v=1",
    record: "6-0-1",
    division: { es: "Peso wélter", en: "Welterweight" },
    height: "—",
    reach: "—",
    stance: { es: "—", en: "—" },
    koRate: "83%",
    debut: "2025-11-22",
    sourceLabel: "BoxRec",
    sourceUrl: "https://boxrec.com/en/box-pro/1219378",
    bio: {
      es: "Boxeador dominicano invicto de peso wélter. Seis victorias profesionales —cinco por nocaut— y un empate, y parte del talento local CFL.",
      en: "Undefeated Dominican welterweight. Six professional wins —five by knockout— plus one draw, and part of CFL’s local talent.",
    },
    recent: [
      { result: "W", opponent: "Juan Carlos Salazar Jose", event: "Dominican Fight Night, Coliseo Carlos Teo Cruz", date: "2026-09-11", method: "TKO · R4" },
      { result: "D", opponent: "Anfenni Diaz", event: "Coliseo Carlos Teo Cruz", date: "2026-05-23", method: "Draw · R6" },
      { result: "W", opponent: "Angel Apolinar Elena Perez", event: "Coco Locos, Sosúa", date: "2026-03-28", method: "TKO · R2" },
      { result: "W", opponent: "Marco Acevedo", event: "Coliseo Carlos Teo Cruz", date: "2026-02-21", method: "KO/TKO · R2" },
      { result: "W", opponent: "Aris Rosario Fabian", event: "La Batalla de Santiago 7", date: "2025-12-14", method: "KO/TKO · R1" },
    ],
  },
};
