window.CFL_FIGHTERS = {
  "ty-jhonson": {
    id: "ty-jhonson",
    name: "Ty “La Pollona” Jhonson",
    namePlain: "Ty Jhonson",
    nickname: "La Pollona",
    sport: { es: "MMA", en: "MMA" },
    country: { es: "Estados Unidos", en: "United States" },
    based: { es: "Punta Cana, República Dominicana", en: "Punta Cana, Dominican Republic" },
    image: "assets/ty-jhonson.png?v=4",
    record: "14-7-0",
    division: { es: "Peso pluma", en: "Featherweight" },
    height: "5′7″ / 170 cm",
    reach: "67.3″ / 171 cm",
    stance: { es: "Ortodoxo", en: "Orthodox" },
    koRate: "14%",
    debut: "2019",
    sourceLabel: "Tapology",
    sourceUrl: "https://www.tapology.com/fightcenter/fighters/114445-ty-kalista",
    bio: {
      es: "Atleta de MMA con recorrido internacional (PFL, Titan FC, XKO) y base en Punta Cana. Conocido por su wrestling y submissions, proyecta el talento CFL hacia escenarios globales.",
      en: "An international MMA competitor (PFL, Titan FC, XKO) based in Punta Cana. Known for wrestling and submissions, he brings CFL talent onto global stages.",
    },
    recent: [
      { result: "W", opponent: "Tarcísio Romano", event: "Peak Fighting 42", date: "2025-01-25", method: "TKO · R3" },
      { result: "L", opponent: "Bryce Meredith", event: "PFL 1 (2024)", date: "2024-04-04", method: "Decision · R3" },
      { result: "W", opponent: "Motaz Askar", event: "Anthony Pettis FC 9", date: "2023-11-19", method: "Decision · R3" },
      { result: "W", opponent: "James Settle", event: "XKO 63", date: "2023-07-28", method: "KO/TKO · R3" },
      { result: "W", opponent: "Jefry Roy", event: "Fighting Force 10", date: "2022-12-09", method: "Submission · R1" },
    ],
  },

  "thomas-blumenfeld": {
    id: "thomas-blumenfeld",
    name: "Thomas Blumenfeld",
    namePlain: "Thomas Blumenfeld",
    nickname: "The Bullet",
    sport: { es: "Boxeo", en: "Boxing" },
    country: { es: "Canadá", en: "Canada" },
    based: { es: "Springfield, Vermont / Canadá", en: "Springfield, Vermont / Canada" },
    image: "assets/thomas-blumenfeld.png?v=4",
    record: "12-0-0",
    division: { es: "Ligero / Superligero", en: "Lightweight / Light welterweight" },
    height: "—",
    reach: "—",
    stance: { es: "Zurdo", en: "Southpaw" },
    koRate: "83%",
    debut: "2022-06-11",
    sourceLabel: "BoxRec",
    sourceUrl: "https://boxrec.com/en/box-pro/864573",
    bio: {
      es: "Prospecto canadiense invicto con plata en los Juegos de la Commonwealth 2018. Southpaw con alto porcentaje de nocauts y proyección internacional hacia la noche CFL en Santo Domingo.",
      en: "Undefeated Canadian prospect and 2018 Commonwealth Games silver medalist. A southpaw with a high knockout rate, lined up for CFL’s Santo Domingo night.",
    },
    recent: [
      { result: "W", opponent: "Willmank Canonico Brito", event: "Mohegan Sun Pocono Downs", date: "2026-03", method: "Decision" },
      { result: "W", opponent: "Cristian Ruben Mino", event: "Mohegan Fall Brawl", date: "2025-11", method: "KO/TKO · R1" },
      { result: "W", opponent: "Julio Rosa", event: "Carteret, NJ", date: "2025-09", method: "KO/TKO · R4" },
      { result: "W", opponent: "Christopher Rodriguez", event: "Carteret, NJ", date: "2025-04", method: "KO/TKO · R3" },
      { result: "W", opponent: "Frankie Sanchez Jr", event: "2300 Arena, Philadelphia", date: "2025-03", method: "KO/TKO · R2" },
    ],
  },

  "vincent-vangogh": {
    id: "vincent-vangogh",
    name: "Vincent “El Cuco” Van Gogh",
    namePlain: "Vincent Van Gogh",
    nickname: "El Cuco",
    sport: { es: "MMA", en: "MMA" },
    country: { es: "República Dominicana", en: "Dominican Republic" },
    based: { es: "Santo Domingo, República Dominicana", en: "Santo Domingo, Dominican Republic" },
    image: "assets/vincent-vangogh.png?v=4",
    record: "6-3-0 (1 NC)",
    division: { es: "Peso pluma", en: "Featherweight" },
    height: "5′8″ / 173 cm",
    reach: "—",
    stance: { es: "Ortodoxo", en: "Orthodox" },
    koRate: "83%",
    debut: "2020",
    sourceLabel: "Tapology",
    sourceUrl: "https://www.tapology.com/fightcenter/fighters/244282-vincent-van-gogh",
    bio: {
      es: "Peso pluma dominicano y campeón FFP. Estilo agresivo con alto porcentaje de finales por KO/TKO, representante local de la cultura de combate en Santo Domingo.",
      en: "Dominican featherweight and FFP champion. Aggressive finisher with a high KO/TKO rate — a hometown face of combat culture in Santo Domingo.",
    },
    recent: [
      { result: "W", opponent: "Juan Carlos Alcantara", event: "Fighting Force 15", date: "2024-10-19", method: "Submission · R1" },
      { result: "NC", opponent: "Edwin Andres Gomez", event: "Fighting Force 14", date: "2024-07-06", method: "No contest · R2" },
      { result: "W", opponent: "Yeison Bayona", event: "Fighting Force 13", date: "2024-02-03", method: "KO · R1" },
      { result: "W", opponent: "Alex Alcantara", event: "Fighting Force 12", date: "2023-09-02", method: "TKO · R1" },
      { result: "L", opponent: "Luis Miguel Aular", event: "Liga Inmortal 2", date: "2023-03-04", method: "TKO · R3" },
    ],
  },

  "yancarlos-perez": {
    id: "yancarlos-perez",
    name: "Yancarlos Perez",
    namePlain: "Yancarlos Perez",
    nickname: "",
    sport: { es: "Boxeo", en: "Boxing" },
    country: { es: "República Dominicana", en: "Dominican Republic" },
    based: { es: "Santo Domingo, República Dominicana", en: "Santo Domingo, Dominican Republic" },
    image: "assets/yancarlos-perez.png?v=4",
    record: "8-1-0",
    division: { es: "Súper gallo", en: "Super bantamweight" },
    height: "5′6″ / 168 cm",
    reach: "—",
    stance: { es: "Ortodoxo", en: "Orthodox" },
    koRate: "63%",
    debut: "2024-06-28",
    sourceLabel: "BoxRec",
    sourceUrl: "https://boxrec.com/en/box-pro/1081310",
    bio: {
      es: "Boxeador dominicano de Villa Mella con debut profesional en 2024. Cartelera activa entre Santo Domingo y Estados Unidos, y parte del talento local CFL.",
      en: "Dominican boxer from Villa Mella who turned pro in 2024. Active between Santo Domingo and the U.S., and part of CFL’s local talent pipeline.",
    },
    recent: [
      { result: "W", opponent: "Carlos Alberto Santana Parra", event: "Coliseo Carlos Teo Cruz", date: "2025-12", method: "Win" },
      { result: "W", opponent: "Gregorio Lebron", event: "Revere, Massachusetts", date: "2025-11", method: "Win" },
      { result: "L", opponent: "Rajon Chance", event: "White Plains, New York", date: "2025-06", method: "Loss" },
      { result: "W", opponent: "Merlito Sabillo", event: "Pueblo, Colorado", date: "2025-05", method: "Win" },
      { result: "W", opponent: "Yeuri Andujar", event: "Huntington, New York", date: "2025-03", method: "Win" },
    ],
  },

  "branny-rosario": {
    id: "branny-rosario",
    name: "Branny Rosario",
    namePlain: "Branny Rosario",
    nickname: "",
    sport: { es: "MMA", en: "MMA" },
    country: { es: "República Dominicana", en: "Dominican Republic" },
    based: { es: "Santo Domingo, República Dominicana", en: "Santo Domingo, Dominican Republic" },
    image: "assets/branny-rosario.png?v=4",
    record: "2-0-0",
    division: { es: "Peso pluma / gallo", en: "Featherweight / Bantamweight" },
    height: "5′9″ / 175 cm",
    reach: "—",
    stance: { es: "Ortodoxo", en: "Orthodox" },
    koRate: "50%",
    debut: "2024-07-06",
    sourceLabel: "Tapology",
    sourceUrl: "https://www.tapology.com/fightcenter/fighters/307205-branny-rosario",
    bio: {
      es: "Prospecto dominicano invicto en MMA profesional. Dos victorias en Fighting Force con finalizaciones en el primer asalto.",
      en: "Undefeated Dominican MMA prospect. Two Fighting Force wins, both first-round finishes.",
    },
    recent: [
      { result: "W", opponent: "Tommy Garcia", event: "Fighting Force 16", date: "2025-08-02", method: "Submission · R1" },
      { result: "W", opponent: "Freddy Mordan", event: "Fighting Force 14", date: "2024-07-06", method: "TKO · R1" },
    ],
  },

  "delffy-humer": {
    id: "delffy-humer",
    name: "Delffy “El Guerrero DD” Humer",
    namePlain: "Delffy Humer",
    nickname: "El Guerrero DD",
    sport: { es: "MMA", en: "MMA" },
    country: { es: "República Dominicana", en: "Dominican Republic" },
    based: { es: "Cabarete / Sosúa, República Dominicana", en: "Cabarete / Sosúa, Dominican Republic" },
    image: "assets/delffy-humer.png?v=4",
    record: "3-0-0",
    division: { es: "Peso mosca", en: "Flyweight" },
    height: "5′8″ / 173 cm",
    reach: "—",
    stance: { es: "Ortodoxo", en: "Orthodox" },
    koRate: "67%",
    debut: "2025-05-17",
    sourceLabel: "Tapology",
    sourceUrl: "https://www.tapology.com/fightcenter/fighters/307971-delffy-humer-el-guerrero-dd",
    bio: {
      es: "Peso mosca dominicano invicto, con experiencia amateur internacional (IMMAF) y tres victorias profesionales en España con The Way of Warrior.",
      en: "Undefeated Dominican flyweight with international amateur experience (IMMAF) and three pro wins in Spain with The Way of Warrior.",
    },
    recent: [
      { result: "W", opponent: "Rafael Gemaque", event: "WOW 27 · Madrid", date: "2026-03-07", method: "TKO · R3" },
      { result: "W", opponent: "Yaman Mjahed", event: "WOW 24 · Vitoria", date: "2025-11-28", method: "KO/TKO · R2" },
      { result: "W", opponent: "Jose Jefferson Cobo Diaz", event: "WOW 19 · Alicante", date: "2025-05-17", method: "Submission · R3" },
    ],
  },
};
